language: node_js

env:
- CODECOV_TOKEN="565f4dce-707a-4fda-a467-ffcc4e24b661"

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

after_success:
  - npm run coverage
  - codecov
  - cat ./coverage/lcov.info | coveralls
  - bash <(curl -s https://codecov.io/bash)
  - gulp codacy
